In [10]:
import pandas as pd

In [11]:
df=pd.read_csv('sales_data.csv')

In [12]:
df.describe()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000
mean,15.665753,2014.401739,35.919212,11.901660,267.296366,452.938427,285.051665,469.318695,754.370360
std,8.781567,1.272510,11.021936,9.561857,549.835483,922.071219,453.887443,884.866118,1309.094674
min,1.000000,2011.000000,17.000000,1.000000,1.000000,2.000000,-30.000000,1.000000,2.000000
25%,8.000000,2013.000000,28.000000,2.000000,2.000000,5.000000,29.000000,28.000000,63.000000
50%,16.000000,2014.000000,35.000000,10.000000,9.000000,24.000000,101.000000,108.000000,223.000000
75%,23.000000,2016.000000,43.000000,20.000000,42.000000,70.000000,358.000000,432.000000,800.000000
max,31.000000,2016.000000,87.000000,32.000000,2171.000000,3578.000000,15096.000000,42978.000000,58074.000000

In [13]:
df.isnull().sum()

Date                0
Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             0
State               0
Product_Category    0
Sub_Category        0
Product             0
Order_Quantity      0
Unit_Cost           0
Unit_Price          0
Profit              0
Cost                0
Revenue             0
dtype: int64

In [14]:
df=df.drop_duplicates()

In [15]:
df

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113031,2016-04-12,12,April,2016,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",3,24,64,112,72,184
113032,2014-04-02,2,April,2014,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113033,2016-04-02,2,April,2016,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113034,2014-03-04,4,March,2014,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",24,24,64,684,576,1260
113035,2016-03-04,4,March,2016,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",23,24,64,655,552,1207

In [17]:
df['Country']=df['Country'].str.lower()

In [18]:
df['Country']

0                 canada
1                 canada
2              australia
3              australia
4              australia
               ...
113031    united kingdom
113032         australia
113033         australia
113034            france
113035            france
Name: Country, Length: 112036, dtype: object

In [19]:
df['Customer_Gender']=df['Customer_Gender'].replace('M','MALE')

In [23]:
df['Customer_Gender']=df['Customer_Gender'].replace('F','FEMALE')

In [25]:
df.head(48)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),MALE,australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),MALE,australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),FEMALE,australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418
5,2016-05-15,15,May,2016,47,Adults (35-64),FEMALE,australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,5,45,120,297,225,522
6,2014-05-22,22,May,2014,47,Adults (35-64),FEMALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,199,180,379
7,2016-05-22,22,May,2016,47,Adults (35-64),FEMALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,2,45,120,100,90,190
8,2014-02-22,22,February,2014,35,Adults (35-64),MALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,22,45,120,1096,990,2086
9,2016-02-22,22,February,2016,35,Adults (35-64),MALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,21,45,120,1046,945,1991
10,2013-07-30,30,July,2013,32,Young Adults (25-34),FEMALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,398,360,758
11,2015-07-30,30,July,2015,32,Young Adults (25-34),FEMALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,398,360,758
12,2013-07-15,15,July,2013,34,Young Adults (25-34),MALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,349,315,664
13,2015-07-15,15,July,2015,34,Young Adults (25-34),MALE,australia,Victoria,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,349,315,664
14,2013-08-02,2,August,2013,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,5,45,120,369,225,594
15,2015-08-02,2,August,2015,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,517,315,832
16,2013-09-02,2,September,2013,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,2,45,120,148,90,238
17,2015-09-02,2,September,2015,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45,120,74,45,119
18,2014-01-22,22,January,2014,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45,120,74,45,119
19,2016-01-22,22,January,2016,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45,120,74,45,119
20,2014-05-17,17,May,2014,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,6,45,120,443,270,713
21,2016-05-17,17,May,2016,29,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
22,2014-03-27,27,March,2014,51,Adults (35-64),MALE,united states,Oregon,Accessories,Bike Racks,Hitch Rack - 4-Bike,9,45,120,524,405,929
23,2016-03-27,27,March,2016,51,Adults (35-64),MALE,united states,Oregon,Accessories,Bike Racks,Hitch Rack - 4-Bike,7,45,120,407,315,722
24,2013-08-25,25,August,2013,49,Adults (35-64),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,3,45,120,221,135,356
25,2015-08-25,25,August,2015,49,Adults (35-64),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45,120,74,45,119
26,2013-12-26,26,December,2013,49,Adults (35-64),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,6,45,120,443,270,713
27,2015-12-26,26,December,2015,49,Adults (35-64),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,5,45,120,369,225,594
28,2014-01-02,2,January,2014,48,Adults (35-64),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,295,180,475
29,2016-01-02,2,January,2016,48,Adults (35-64),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,295,180,475
30,2014-03-13,13,March,2014,48,Adults (35-64),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1476,900,2376
31,2016-03-13,13,March,2016,48,Adults (35-64),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,22,45,120,1624,990,2614
32,2014-05-23,23,May,2014,47,Adults (35-64),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,24,45,120,1771,1080,2851
33,2016-05-23,23,May,2016,47,Adults (35-64),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1697,1035,2732
34,2013-07-19,19,July,2013,32,Young Adults (25-34),FEMALE,united states,Oregon,Accessories,Bike Racks,Hitch Rack - 4-Bike,9,45,120,524,405,929
35,2015-07-19,19,July,2015,32,Young Adults (25-34),FEMALE,united states,Oregon,Accessories,Bike Racks,Hitch Rack - 4-Bike,9,45,120,524,405,929
36,2013-11-11,11,November,2013,34,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,25,45,120,1845,1125,2970
37,2015-11-11,11,November,2015,34,Young Adults (25-34),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1697,1035,2732
38,2013-07-13,13,July,2013,43,Adults (35-64),FEMALE,united states,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,10,45,120,726,450,1176
39,2015-07-13,13,July,2015,43,Adults (35-64),FEMALE,united states,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,10,45,120,726,450,1176
40,2014-03-31,31,March,2014,43,Adults (35-64),FEMALE,united states,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,11,45,120,799,495,1294
41,2016-03-31,31,March,2016,43,Adults (35-64),FEMALE,united states,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,11,45,120,799,495,1294
42,2013-08-28,28,August,2013,61,Adults (35-64),MALE,united states,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,581,360,941
43,2015-08-28,28,August,2015,61,Adults (35-64),MALE,united states,California,Accessories,Bike Racks,Hitch Rack - 4-Bike,10,45,120,726,450,1176
44,2013-08-27,27,August,2013,57,Adults (35-64),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,2,45,120,148,90,238
45,2015-08-27,27,August,2015,57,Adults (35-64),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,1,45,120,74,45,119
46,2013-11-17,17,November,2013,29,Young Adults (25-34),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,12,45,120,886,540,1426
47,2015-11-17,17,November,2015,29,Young Adults (25-34),FEMALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,14,45,120,1033,630,1663

In [28]:
df['Country'].head(10)

0       canada
1       canada
2    australia
3    australia
4    australia
5    australia
6    australia
7    australia
8    australia
9    australia
Name: Country, dtype: object

In [54]:
df["Date"] = pd.to_datetime(df["Date"])

In [58]:
df['Date']=df['Date'].dt.strftime('%d-%m-%Y')

In [59]:
df['Customer_Age'].dtype

dtype('int64')

In [65]:
df

,date,day,month,year,customer_age,age_group,customer_gender,country,state,product_category,sub_category,product,order_quantity,unit_cost,unit_price,profit,cost,revenue
0,26-11-2013,26,November,2013,19,Youth (<25),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,26-11-2015,26,November,2015,19,Youth (<25),MALE,canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,23-03-2014,23,March,2014,49,Adults (35-64),MALE,australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,23-03-2016,23,March,2016,49,Adults (35-64),MALE,australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,15-05-2014,15,May,2014,47,Adults (35-64),FEMALE,australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113031,12-04-2016,12,April,2016,41,Adults (35-64),MALE,united kingdom,England,Clothing,Vests,"Classic Vest, S",3,24,64,112,72,184
113032,02-04-2014,2,April,2014,18,Youth (<25),MALE,australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113033,02-04-2016,2,April,2016,18,Youth (<25),MALE,australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113034,04-03-2014,4,March,2014,37,Adults (35-64),FEMALE,france,Seine (Paris),Clothing,Vests,"Classic Vest, L",24,24,64,684,576,1260
113035,04-03-2016,4,March,2016,37,Adults (35-64),FEMALE,france,Seine (Paris),Clothing,Vests,"Classic Vest, L",23,24,64,655,552,1207

In [64]:
df.columns=df.columns.str.lower()

In [63]:
df['day'].dtype

dtype('int64')

In [67]:
df['order_quantity'].dtype

dtype('int64')

In [69]:
df['unit_price'].dtype

dtype('int64')

In [71]:
df['profit'].dtype

dtype('int64')

In [74]:
df['revenue'].dtype

dtype('int64')

In [76]:
df.to_csv('salesdata_cleaned')